### ISSUE TITLE
BluePrint should not be public API

### ISSUE THREAD

**Issue by rjrjr** [square/mortar#104]
Especially after the introduction of @WithModule

**Comment by cpetosky** [comment]
I see ebc7707669c36740fc17f887f4eaa2e8001e39ca removed Blueprint generally, but the README still refers to things in terms of Blueprint.

Is there a timeline for updated best practices with Mortar? I'm interested in porting an existing app to it.

(Sorry if this is the wrong forum to ask this -- didn't see a mailing list or similar.)

**Comment by rjrjr** [comment]
We're trying to get the momentum back up — we need it too, especially as
Dagger 2 approaches and Google starts to improve testing.

Anyway, don't want to make promises I won't keep, but I'm hoping you'll see
a steady trickle of work over the next few weeks. In the meantime, our
shipping apps are based on the versions currently in Maven central, which
have been stable for a while. FWIW.

**Comment by pyricau** [comment]
@rjrjr we should close this issue, right? BluePrint being dead, it's definitely not a public API.

@cpetosky yep we need to update the readme.
