### ISSUE TITLE
Bootstrap Package/Library

### ISSUE THREAD

**Issue by AndrewReitz** [square/mortar#106]
I really like the idea behind mortar, but I feel like getting up and running takes a lot of work to get a project off the ground.

I would like to propose something that has most of the bootstrapping tasks done already. Either a project template or a separate library with a MortarApplication and MortarActivity that users would inherit from.

Some other things that might be nice to include would be the classes under the com.example.mortar.util package.

I would be interested in hearing what others think about this idea.

**Comment by kuhnza** [comment]
I realise I'm a bit late to the party but I've knocked up a Yeoman generator that creates a skeleton app using mortar+flow and contains a bunch of helpful test utilities and examples to get you started: https://github.com/kuhnza/generator-android-square-stack

I'd also welcome any feedback/contributions.
