### ISSUE TITLE
onSave with getView() == null

### ISSUE THREAD

**Issue by konmik** [square/mortar#108]
When I have a view with presenter, and flip device's screen with a short delay 4 times, onSave is being called multiple times (about 7 - 10 times for each flip) with getView() == null and each time with a different scope. Should I provide you some code or it is expected behavior?

P.S. Could you please explain why are you using application's scope to save view's bundle? Looks not very logical to me. We're getting onLoad() before view restores it's state, so when I try to publish some info from onLoad(), it is erased by View's onRestoreInstanceState. I would suggest to call onLoad during view's onAttachedToWindow, after view's state restoration complete.

**Comment by Zhuinden** [comment]
This isn't a closed issue at all! I'm using only one instance of the view, yet with enough rotations, there are times when `onSave()` is called with no view! I'd expect there to be a View each time for `onSave()`, otherwise there's no real point (unless you move ALL STATE to the presenter, which is pretty rough).

    E/AndroidRuntime: java.lang.NullPointerException
    E/AndroidRuntime:     at CameraPresenter.onSave(CameraPresenter.java:29)
    E/AndroidRuntime:     at mortar.Presenter$1.onSave(Presenter.java:42)
    E/AndroidRuntime:     at mortar.bundler.BundleService.saveToRootBundle(BundleService.java:135)
    E/AndroidRuntime:     at mortar.bundler.BundleServiceRunner.onSaveInstanceState(BundleServiceRunner.java:97)
    E/AndroidRuntime:     at MainActivity.onSaveInstanceState(MainActivity.java:144)
    E/AndroidRuntime:     at android.app.Activity.performSaveInstanceState(Activity.java:1153)

Now i'll have to drop the view in case of `onStop()` and `onExitScope()` instead.

**Comment by konmik** [comment]
Afaik, this issue can be solved by using flow library.

**Comment by Zhuinden** [comment]
@konmik I am using Flow and this still happened when rotating from landscape to portrait (90 degrees) to portrait (180 degrees) with the right timing.

**Comment by konmik** [comment]
Oh, I didn't actually try it with flow actually. It is the other issue as I think.

**Comment by Zhuinden** [comment]
@konmik honestly, now I'm running into the issue with Flow that the `onSave()` is not triggered on Flow transition (only on configuration change) or `dropView()`, but `onLoad()` is triggered on `takeView()`...

I think I'm starting to dislike `ViewPresenter<V>`. I've always kinda had my concerns about it, but now I feel like I probably just have to make my own.
