### ISSUE TITLE
How to test the presenter ?

### ISSUE THREAD

**Issue by tbruyelle** [square/mortar#111]
One of the best benefit of dealing with Presenters is test writing. Your test class extends `AndroidTestCase`, you mock all the presenter's dependencies and you can start. That's how I did before I start to work with Mortar.

With Mortar you have to invoke `takeView()` to inject your (mocked) view in the presenter. And `takeView()` invokes `view.getContext().getSystemService()`, which results to NPE because `Context` isn't mockable.

How to test the presenter with Mortar ?

**Comment by spierce7** [comment]
@rjrjr Did you guys end up sticking with the pattern shown above, or have you found something better?

**Comment by rjrjr** [comment]
http://www.bignerdranch.com/blog/all-in-together-android-studio-gradle-and-robolectric/

**Comment by rjrjr** [comment]
And we're eagerly waiting for Google's promised junit support.

**Comment by tbruyelle** [comment]
A first step forward, no more final methods ! http://tools.android.com/tech-docs/unit-testing-support

**Comment by spierce7** [comment]
@rjrjr Where did you guys end up falling on this?

**Comment by takn** [comment]
@rjrjr how did you end up doing this?

**Comment by xfumihiro** [comment]
Here's an [easy approach](https://github.com/xfumihiro/UnitTestMortar).
