### ISSUE TITLE
Publish snapshot to Sonatype?

### ISSUE THREAD

**Issue by codeprogression** [square/mortar#119]
The current samples for Mortar and Flow are based on [0.17-SNAPSHOT](https://github.com/square/mortar/blob/master/mortar-sample/pom.xml#L27) and [0.9-SNAPSHOT](https://github.com/square/mortar/blob/master/mortar-sample/pom.xml#L62), respectively. I am assuming those snapshots are on your internal or local maven repositories (I cannot find them on https://oss.sonatype.org/content/repositories/snapshots/). 

Would you consider publishing those snapshots to the Sonatype snapshot repo?

**Comment by rjrjr** [comment]
You bet.

**Comment by rjrjr** [comment]
Done, I think. Can you confirm that they're working for you in a few hours
(given Sonatype lag times)?

**Comment by codeprogression** [comment]
Working for me. Thanks much!
