### ISSUE TITLE
New Version?

### ISSUE THREAD

**Issue by tsilvia** [square/mortar#126]
In your readme.md you make reference to a `buildRootScope()`. However, if someone uses your latest published version of v0.16 this will not be available as this was added about 28 days ago. https://github.com/square/mortar/blob/master/mortar/src/main/java/mortar/MortarScope.java#L46

I understand that you put a disclosure on your readme as well that this is in rapid development, and you can't promise breaking changes won't happen. However, it seems confusing to a new user to not be able to implement the example of the readme with the latest version that is published to public gradle / maven repositories.

I understand that this might not be a top priority, but I just wanted to bring it to your attention.

**Comment by rjrjr** [comment]
This is not the version published to the repo, it's the tip of master. See
https://github.com/square/mortar/tree/0a3b52e972003748da1a7bd54287083390ffafcf

**Comment by jkoorts** [comment]
This caught me too. Luckily there was a post for this :)

**Comment by jkoorts** [comment]
Btw, compile 'com.squareup.mortar:mortar:0.17-SNAPSHOT' does not work

**Comment by jkoorts** [comment]
On 1.6 the doc sample does this:

 Mortar.getMortarScope(this);

the 1.6 lib does not support that method.

:(

**Comment by rjrjr** [comment]
0.17 has been released.
