### ISSUE TITLE
Is Mortar still alive?

### ISSUE THREAD

**Issue by andrewtoth** [square/mortar#194]
The last activity by a maintainer was six months ago. Is this project still alive? It is definitely a big improvement over current Android lifecycles, but is it still being maintained? The lack of documentation is a huge hindrance, and is very uncharacteristic of a Square maintained OSS project.

**Comment by rjrjr** [comment]
See https://github.com/square/flow/issues/203

**Comment by Zhuinden** [comment]
@andrewtoth Mortar ViewPresenters suck and don't integrate with anything, so I definitely recommend that you avoid it.

MortarScopes are OK
