### ISSUE TITLE
Is Mortar still active?

### ISSUE THREAD

**Issue by ScottPierce** [square/mortar#198]
I was wondering if Mortar development was still active. I noticed that there are some issues filed with no responses. https://github.com/square/flow seems to be active. I'm considering mortar for use in a project.

**Comment by rjrjr** [comment]
It is active, but it's slow. And yes, Flow is getting more attention at the moment. 

The two libraries are complimentary, and our main app uses both. But with that said, Flow is increasingly able to solve a lot the problems that Mortar addresses on its own. If I were starting from scratch I'd start just with Flow and RxJava, and add Mortar later when I found a need for scoping.
