### ISSUE TITLE
I recently inherited a mortar+flow codebase

### ISSUE THREAD

**Issue by dcow** [square/mortar#199]
There's literally an `ActivityLifecyclePresenter` that has all the Android lifecycle added back. It's a canonical case of *blog post coding*. We have ViewPresenters everywhere that are overly-coupled to mortar but use none of the scoping. This is only a tiny rant. I'm looking for advice on how to proceed. Given that this project hasn't been touched in months, do I rip out mortar and stick with flow+rxandroid, or do you see this ~~library~~ framework reaching a 1.0 release anytime in the next 2 years?

**Comment by rjrjr** [comment]
flow+rxandroid sounds like a fine idea.
