### ISSUE TITLE
Use ContextWrapper#attachBaseContext to reduce boilerplate?

### ISSUE THREAD

**Issue by rjrjr** [square/mortar#85]
Can we use ContextWrapper#attachBaseContext to make it easier to set up the Application and Activity scopes w/o requiring getSystemService boilerplate?

Remember that attachBaseContext is a one-shot method. Should make such a mechanism a convenience, not a requirement, so that we don't screw over apps that might be using that hook already.

**Comment by Zhuinden** [comment]
And yet, Flow 1.0 uses this mechanism

**Comment by loganj** [comment]
Flow would have a _lot_ more boilerplate otherwise. Mortar's boilerplate level is about the same either way.

**Comment by Zhuinden** [comment]
I see! :smile:
